// generated by "comer add-with-tpl"
// © 2024 IMOOWI. All Rights Reserved.
//
//	@Author	yuanjun<imoowi@qq.com>
package services

import (
	"github.com/imoowi/examples/comer_add_with_tpl/internal/global"
	"github.com/imoowi/examples/comer_add_with_tpl/internal/models"
	"github.com/imoowi/examples/comer_add_with_tpl/internal/util/response"
	"github.com/imoowi/examples/comer_add_with_tpl/pkg/frame"
)

var PostPlus2 *PostPlus2Service

func RegisterPostPlus2Service(s *PostPlus2Service) {
	PostPlus2 = s
}

type PostPlus2Service struct {
	PostPlus2Repo *models.PostPlus2Repo
}

func newPostPlus2Service(r *models.PostPlus2Repo) *PostPlus2Service {
	return &PostPlus2Service{
		PostPlus2Repo: r,
	}
}

func init() {
	global.Container.Provide(newPostPlus2Service)
	global.RegisterContainerProviders(RegisterPostPlus2Service)
}

func (s *PostPlus2Service) All(c *frame.Context, query *models.PostPlus2Query) (res []*models.PostPlus2, err error) {
	res, err = s.PostPlus2Repo.All(c, query)
	return
}
func (s *PostPlus2Service) PageList(c *frame.Context, req *models.PostPlus2Query) (res *response.PageList, err error) {
	res, err = s.PostPlus2Repo.PageList(c, req)
	return
}

func (s *PostPlus2Service) One(c *frame.Context, id uint) (model *models.PostPlus2, err error) {
	model, err = s.PostPlus2Repo.One(c, id)
	return
}

func (s *PostPlus2Service) OneByName(c *frame.Context, name string) (model *models.PostPlus2, err error) {
	model, err = s.PostPlus2Repo.OneByName(c, name)
	return
}

func (s *PostPlus2Service) Add(c *frame.Context, _model *models.PostPlus2) (newId uint, err error) {
	// model, err := s.PostPlus2Repo.OneByName(c, _model.Name)
	// if model != nil && model.ID > 0 {
	// 	newId = 0
	// 	err = errors.New(`name existed`)
	// 	return
	// }
	_model.ProjectId = c.GetUint(`project_id`)
	newId, err = s.PostPlus2Repo.Add(c, _model)
	return
}

func (s *PostPlus2Service) Update(c *frame.Context, _model *models.PostPlus2, id uint) (updated bool, err error) {
	_model.ProjectId = c.GetUint(`project_id`)
	updated, err = s.PostPlus2Repo.Update(c, _model, id)
	return
}
func (s *PostPlus2Service) Delete(c *frame.Context, id uint) (deleted bool, err error) {
	deleted, err = s.PostPlus2Repo.Delete(c, id)
	return
}
