/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package apps

import (
	_ "{{.moduleName}}/apps/common"
	_ "{{.moduleName}}/apps/swagger"
	_ "{{.moduleName}}/apps/user"
)
