/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package cmd

import (
	"log"

	"github.com/spf13/cobra"
	"{{.moduleName}}/global"
)

// migrateCmd represents the migrate command
var migrateCmd = &cobra.Command{
	Use:          "migrate",
	Short:        "数据迁移",
	Example:      "{{.exeName}} migrate",
	SilenceUsage: true,
	PreRun: func(cmd *cobra.Command, args []string) {
	},
	RunE: func(cmd *cobra.Command, args []string) error {
		return migrate()
	},
}

func init() {
	rootCmd.AddCommand(migrateCmd)

	// Here you will define your flags and configuration settings.

	// Cobra supports Persistent Flags which will work for this command
	// and all subcommands, e.g.:
	// migrateCmd.PersistentFlags().String("foo", "", "A help for foo")

	// Cobra supports local flags which will only run when this command
	// is called directly, e.g.:
	// migrateCmd.Flags().BoolP("toggle", "t", false, "Help message for toggle")
}

func migrate() error {
	log.Println(`migrate start.`)
	global.BootMigrate()
	log.Println(`migrate end.`)
	return nil
}
