// generated by "comer add-with-tpl"
// © 2024 IMOOWI. All Rights Reserved.
//
//	@Author	yuanjun<imoowi@qq.com>
package migrates

import (
	"github.com/imoowi/examples/comer_add_with_tpl/internal/global"
	"github.com/imoowi/examples/comer_add_with_tpl/internal/models"
	"github.com/imoowi/examples/comer_add_with_tpl/pkg/container"
	"github.com/imoowi/examples/comer_add_with_tpl/pkg/mysql"
)

func init() {
	global.Migrate.Provide(doPostPlus2Migrate, container.WithGroup("designer", "monitor"))
}
func doPostPlus2Migrate(db *mysql.MysqlODM) {
	//表注释请自行修改
	db.Client.Set("gorm:table_options", "ENGINE=InnoDB,COMMENT='PostPlus2表'").AutoMigrate(&models.PostPlus2{})
}
