// generated by "comer add-with-tpl"
// © 2024 IMOOWI. All Rights Reserved.
//
//	@Author	yuanjun<imoowi@qq.com>
package controllers

import (
	"net/http"

	"github.com/imoowi/examples/comer_add_with_tpl/internal/global"
	"github.com/imoowi/examples/comer_add_with_tpl/internal/models"
	"github.com/imoowi/examples/comer_add_with_tpl/internal/services"
	"github.com/imoowi/examples/comer_add_with_tpl/pkg/frame"

	"github.com/spf13/cast"
)

// @Summary	分页列表(pagelist)
// @Tags		PostPlus2(页面加)
// @Accept		application/json
// @Produce	application/json
// @Param		Authorization	header		string				true	"Bearer 用户令牌"
//
//	@Param		{object}		query		models.PostPlus2Query	false	"请求参数"
//
// @Success	200				{object}	response.PageList	"成功"
// @Failure	400				{object}	string				"请求错误"
// @Failure	401				{object}	string				"token验证失败"
// @Failure	500				{object}	string				"内部错误"
// @Router		/api/projects/{project_id}/post-plus2s [get]
func PostPlus2PageList(c *frame.Context) {
	var req models.PostPlus2Query
	err := c.ShouldBindQuery(&req)
	if err != nil {
		c.ResponseErr(err.Error(), http.StatusBadRequest)
		return
	}
	if 0 >= req.PageSize {
		result, err := services.PostPlus2.All(c, &req)
		if err != nil {
			c.ResponseErr(err.Error(), http.StatusBadRequest)
			return
		}
		c.ResponseOk(result)
		return
	}
	result, err := services.PostPlus2.PageList(c, &req)
	if err != nil {
		c.ResponseErr(err.Error(), http.StatusBadRequest)
		return
	}
	c.ResponseOk(result)
}

// @Summary	详情(one)
// @Tags		PostPlus2(页面加)
// @Accept		application/json
// @Produce	application/json
// @Param		Authorization	header	string	true	"Bearer 用户令牌"
// @Param		id				path	int		true	"id"
// @Success	200
// @Failure	400	{object}	string	"请求错误"
// @Failure	401	{object}	string	"token验证失败"
// @Failure	500	{object}	string	"内部错误"
// @Router		/api/projects/{project_id}/post-plus2s/{id} [get]
func PostPlus2One(c *frame.Context) {
	id := c.Param(`id`)
	if id == `` {
		c.ResponseErr(`pls input id`, http.StatusBadRequest)
		return
	}
	one, err := services.PostPlus2.One(c, cast.ToUint(id))
	if err != nil {
		c.ResponseErr(err.Error(), http.StatusBadRequest)
		return
	}
	c.ResponseOk(one)
}

// @Summary	新增(add)
// @Tags		PostPlus2(页面加)
// @Accept		application/json
// @Produce	application/json
// @Param		Authorization	header	string		true	"Bearer 用户令牌"
// @Param		{object}		body	models.Page	true	"body"
// @Success	200
// @Failure	400	{object}	string	"请求错误"
// @Failure	401	{object}	string	"token验证失败"
// @Failure	500	{object}	string	"内部错误"
// @Router		/api/projects/{project_id}/post-plus2s [post]
func PostPlus2Add(c *frame.Context) {
	var page *models.PostPlus2
	err := c.ShouldBindJSON(&page)
	if err != nil {
		c.ResponseErr(err.Error(), http.StatusBadRequest)
		return
	}
	newId, err := services.PostPlus2.Add(c, page)
	if err != nil {
		c.ResponseErr(err.Error(), http.StatusBadRequest)
		return
	}
	c.Set(`user_log_obj_id`, newId)
	c.Set(`user_log_res_type`, global.RES_TYPE_NULL)
	c.ResponseOk(newId)
}

// @Summary	更新(update)
// @Tags		PostPlus2(页面加)
// @Accept		application/json
// @Produce	application/json
// @Param		Authorization	header	string		true	"Bearer 用户令牌"
// @Param		id				path	int			true	"id"
// @Param		{object}		body	models.Page	true	"body"
// @Success	200
// @Failure	400	{object}	string	"请求错误"
// @Failure	401	{object}	string	"token验证失败"
// @Failure	500	{object}	string	"内部错误"
// @Router		/api/projects/{project_id}/post-plus2s/{id} [put]
func PostPlus2Update(c *frame.Context) {
	id := c.Param(`id`)
	if id == `` {
		c.ResponseErr(`pls input id`, http.StatusBadRequest)
		return
	}
	var page *models.PostPlus2
	err := c.ShouldBindJSON(&page)
	if err != nil {
		c.ResponseErr(err.Error(), http.StatusBadRequest)
		return
	}
	updated, err := services.PostPlus2.Update(c, page, cast.ToUint(id))
	if err != nil {
		c.ResponseErr(err.Error(), http.StatusBadRequest)
		return
	}
	c.Set(`user_log_obj_id`, id)
	c.Set(`user_log_res_type`, global.RES_TYPE_NULL)
	c.ResponseOk(updated)
}

// @Summary	删除(delete)
// @Tags		PostPlus2(页面加)
// @Accept		application/json
// @Produce	application/json
// @Param		Authorization	header	string	true	"Bearer 用户令牌"
// @Param		id				path	int		true	"id"
// @Success	200
// @Failure	400	{object}	string	"请求错误"
// @Failure	401	{object}	string	"token验证失败"
// @Failure	500	{object}	string	"内部错误"
// @Router		/api/projects/{project_id}/post-plus2s/{id} [delete]
func PostPlus2Del(c *frame.Context) {
	id := c.Param(`id`)
	if id == `` {
		c.ResponseErr(`pls input id`, http.StatusBadRequest)
		return
	}
	deleted, err := services.PostPlus2.Delete(c, cast.ToUint(id))
	if err != nil {
		c.ResponseErr(err.Error(), http.StatusBadRequest)
		return
	}
	c.Set(`user_log_obj_id`, id)
	c.Set(`user_log_res_type`, global.RES_TYPE_NULL)
	c.ResponseOk(deleted)
}
