/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package main

import "{{.moduleName}}/cmd"

// @title           Comer API
// @version         1.0
// @description     This is a comer-example server.
func main() {
	cmd.Execute()
}
