/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package global

type RES_TYPE uint

const (
	RES_TYPE_NULL          RES_TYPE = iota
	RES_TYPE_USER                   //用户
	RES_TYPE_ROLE                   //角色
	RES_TYPE_USERROLE               //用户角色
	RES_TYPE_PAGE                   //页面
	RES_TYPE_PAGETEMPLATE           //页面模板
	RES_TYPE_PROJECT                //项目
)

var ResTypes = map[RES_TYPE]string{
	RES_TYPE_USER:          `用户`,
	RES_TYPE_ROLE:          `角色`,
	RES_TYPE_USERROLE:      `用户角色`,
	RES_TYPE_PAGE:          `页面`,
	RES_TYPE_PAGETEMPLATE:  `页面模板`,
	RES_TYPE_PROJECT:       `项目`,
}

type USER_LOG_TYPE uint

const (
	USER_LOG_TYPE_NULL        USER_LOG_TYPE = iota
	USER_LOG_TYPE_USER_LOGIN                //登录
	USER_LOG_TYPE_USER_LOGOUT               //退出
	USER_LOG_TYPE_USER_CHGPWD               //改密

	USER_LOG_TYPE_GET    //访问
	USER_LOG_TYPE_ADD    //添加
	USER_LOG_TYPE_UPDATE //修改
	USER_LOG_TYPE_DELETE //删除

)
