/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package global

import (
	"log"

	"github.com/imoowi/comer/components"
)

var MysqlDb *components.MysqlODM

// 初始化mysql
func initMysql() {
	// 获取logger相关的配置信息
	config := Config.Sub("mysql")
	var mysqlConfig *components.MysqlODMConfig
	err := config.Unmarshal(&mysqlConfig)
	if err != nil {
		log.Fatal(err)
	}
	mode := Config.GetString("application.mode")
	mysqlConfig.Mode = mode
	MysqlDb = components.NewMysqlODM(mysqlConfig)
}
