// generated by "comer add-with-tpl"
// © 2024 IMOOWI. All Rights Reserved.
//
//	@Author	yuanjun<imoowi@qq.com>
package router

import (
	"github.com/imoowi/examples/comer_add_with_tpl/internal/controllers"
	"github.com/imoowi/examples/comer_add_with_tpl/internal/global"
	"github.com/imoowi/examples/comer_add_with_tpl/internal/middleware"
	"github.com/imoowi/examples/comer_add_with_tpl/pkg/frame"
)

func init() {
	global.RouterProvider.Provide(registerPostPlus2API)
}

func registerPostPlus2API(e *frame.Engine) {
	api := e.Group("/api")
	{
		api.Use(middleware.AuthMiddleware())
		// api.Use(middleware.JWTAuthMiddleware())
		// api.Use(middleware.CasbinMiddleware())
		// api.Use(middleware.UserLogMiddleware())
		pages := api.Group("/post-plus2s")
		{
			//project/:project_id/post-plus2s
			pages.GET("", controllers.PostPlus2PageList) //分页列表
			pages.GET("/:id", controllers.PostPlus2One)  //详情
		}
	}
}
