/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package global

func Bootstrap() {
	// defer initContainerProviders()
	initLog()
	initMysql()
	initRedis()
	initCasbin()
}

func BootMigrate() {
	// defer initMigrateContainerProviders()
	initMysql()
	initCasbin()
}
