// generated by "comer add-with-tpl"
// © 2024 IMOOWI. All Rights Reserved.
//
//	@Author	yuanjun<imoowi@qq.com>
package models

import (
	"github.com/imoowi/examples/comer_add_with_tpl/internal/common"
	"github.com/imoowi/examples/comer_add_with_tpl/internal/util/request"
)

type PostPlus struct {
	common.GormModel        //公共部分，id,created_at,updated_at,deleted_at
	ProjectId        uint   `json:"project_id,string" gorm:"column:project_id;type:int(11);not null;comment:项目id"` //项目id
	Name             string `json:"name" gorm:"column:name;type:varchar(30);not null;comment:页面名称"`                //页面名

}

type PostPlusQuery struct {
	request.PageList
}
