/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package {{.appName}}

import (
	"github.com/gin-gonic/gin"
	_ "{{.ModuleName}}/apps/{{.appName}}/migrates"
	"{{.ModuleName}}/middlewares"
	"{{.ModuleName}}/apps/{{.appName}}/handlers"
	"{{.ModuleName}}/router"
)

func init() {
	router.RegisterRoute(Routers)
}

func Routers(e *gin.Engine) {
	api := e.Group("/api")
	api.Use(middlewares.JWTAuthMiddleware())
	api.Use(middlewares.CasbinMiddleware())
	{{.lHandlerName}}s := api.Group("/{{.handlerName2Dash}}s")
	{
		{{.lHandlerName}}s.GET("", handlers.{{.HandlerName}}PageList, middlewares.UserLogMiddleware()) //分页
		{{.lHandlerName}}s.GET("/:id", handlers.{{.HandlerName}}One, middlewares.UserLogMiddleware()) //一个
		{{.lHandlerName}}s.POST("", handlers.{{.HandlerName}}Add, middlewares.UserLogMiddleware()) //新增
		{{.lHandlerName}}s.PUT("/:id", handlers.{{.HandlerName}}Update, middlewares.UserLogMiddleware()) //更新
		{{.lHandlerName}}s.PATCH("/:id", handlers.{{.HandlerName}}Patch, middlewares.UserLogMiddleware()) //部分更新
		{{.lHandlerName}}s.DELETE("/:id", handlers.{{.HandlerName}}Del, middlewares.UserLogMiddleware()) //默认为软删除
	}

	//!import:do-not-delete-this-line,不要删除此行，主要用于代码生成器
}
