// generated by "comer add-with-tpl"
// © 2024 IMOOWI. All Rights Reserved.
//
//	@Author	yuanjun<imoowi@qq.com>
package migrates

import (
	"{{.ModuleName}}/internal/global"
	"{{.ModuleName}}/internal/models"
	"{{.ModuleName}}/pkg/container"
	"{{.ModuleName}}/pkg/mysql"
)

func init() {
	global.Migrate.Provide(do{{.ModelName}}Migrate, container.WithGroup("designer", "monitor"))
}
func do{{.ModelName}}Migrate(db *mysql.MysqlODM) {
	//表注释请自行修改
	db.Client.Set("gorm:table_options", "ENGINE=InnoDB,COMMENT='{{.ModelName}}表'").AutoMigrate(&models.{{.ModelName}}{})
}
