// generated by "comer add-with-tpl"
// © 2024 IMOOWI. All Rights Reserved.
//
//	@Author	yuanjun<imoowi@qq.com>
package models

import (
	"errors"

	"// generated by "comer add-with-tpl"
// © 2024 IMOOWI. All Rights Reserved.
//
//	@Author	yuanjun<imoowi@qq.com>/internal/global"
	"{{.ModuleName}}/internal/util/response"
	"{{.ModuleName}}/pkg/frame"
	"{{.ModuleName}}/pkg/mysql"

	"github.com/spf13/cast"
)

type {{.ModelName}}Repo struct {
	db *mysql.MysqlODM
}

func new{{.ModelName}}Repo() *{{.ModelName}}Repo {
	return &{{.ModelName}}Repo{
		db: global.MysqlDb,
	}
}
func init() {
	global.Container.Provide(new{{.ModelName}}Repo)
}

func (r *{{.ModelName}}Repo) All(c *frame.Context, query *{{.ModelName}}Query) (res []*{{.ModelName}}, err error) {
	db := r.db.Client
	if query.SearchKey != `` {
		db = db.Where(`name LIKE ?`, `%`+query.SearchKey+`%`)
	}
	projectId := c.GetUint(`project_id`)
	if projectId > 0 {
		db = db.Where(`project_id=?`, projectId)
	}
	err = db.Find(&res).Error
	//	if errors.Is(err, gorm.ErrRecordNotFound) {
	//		err = nil
	//	}
	return
}
func (r *{{.ModelName}}Repo) PageList(c *frame.Context, req *{{.ModelName}}Query) (res *response.PageList, err error) {
	db := r.db.Client
	var pages []*{{.ModelName}}

	if req.SearchKey != `` {
		db = db.Where(`name LIKE ?`, `%`+req.SearchKey+`%`)
	}
	projectId := c.GetUint(`project_id`)
	if projectId > 0 {
		db = db.Where(`project_id=?`, projectId)
	}
	offset := (req.Page - 1) * req.PageSize
	db = db.Offset(int(offset)).Limit(int(req.PageSize))
	// db=db.Order(`name desc`)
	err = db.Find(&pages).Error
	//	if errors.Is(err, gorm.ErrRecordNotFound) {
	//		err = nil
	//	}

	var count int64
	db.Offset(-1).Limit(-1).Count(&count)

	res = &response.PageList{
		List:  pages,
		Pages: response.MakePages(count, req.Page, req.PageSize),
	}
	return
}

func (r *{{.ModelName}}Repo) One(c *frame.Context, id uint) (page *{{.ModelName}}, err error) {
	cacheKey := `page_models_{{.ModelName}}Repo_One_` + cast.ToString(id)
	if data, ok := global.GlobalCache.Load(cacheKey); ok {
		if data != nil {
			return data.(*{{.ModelName}}), nil
		}
	}

	db := r.db.Client
	err = db.Where(`id=?`, id).First(&page).Error
	// if errors.Is(err, gorm.ErrRecordNotFound) {
	// 	err = nil
	// }
	if page != nil && page.ID > 0 {
		global.GlobalCache.Store(cacheKey, page)
	}
	return
}

func (r *{{.ModelName}}Repo) OneByName(c *frame.Context, name string) (page *{{.ModelName}}, err error) {
	db := r.db.Client
	err = db.Where(`name=?`, name).First(&page).Error
	// if errors.Is(err, gorm.ErrRecordNotFound) {
	// 	err = nil
	// }
	return
}

func (r *{{.ModelName}}Repo) Add(c *frame.Context, model *{{.ModelName}}) (newId uint, err error) {

	db := r.db.Client
	db = db.Create(&model)
	err = db.Error

	newId = model.ID
	return
}

func (r *{{.ModelName}}Repo) Update(c *frame.Context, model *{{.ModelName}}, id uint) (updated bool, err error) {
	if id == 0 {
		updated = false
		err = errors.New(`pls input id`)
		return
	}
	model.ID = id
	db := r.db.Client
	err = db.Omit(`created_at`).Save(&model).Error
	if err == nil {
		updated = true
		cacheKey := `page_models_{{.ModelName}}Repo_One_` + cast.ToString(id)
		global.GlobalCache.Delete(cacheKey)
	}
	return
}

func (r *{{.ModelName}}Repo) Delete(c *frame.Context, id uint) (deleted bool, err error) {
	if id == 0 {
		deleted = false
		err = errors.New(`pls input id`)
		return
	}
	db := r.db.Client
	model, err := r.One(c, id)
	if err != nil {
		return
	}
	if model.ID == 0 {
		err = errors.New(`obj not existe`)
		return
	}
	err = db.Delete(&model).Error
	if err == nil {
		deleted = true
		cacheKey := `page_models_{{.ModelName}}Repo_One_` + cast.ToString(id)
		global.GlobalCache.Delete(cacheKey)
	}
	return
}
