// generated by "comer add-with-tpl"
// © 2024 IMOOWI. All Rights Reserved.
//
//	@Author	yuanjun<imoowi@qq.com>
package router

import (
	"{{.ModuleName}}/internal/controllers"
	"{{.ModuleName}}/internal/global"
	"{{.ModuleName}}/internal/middleware"
	"{{.ModuleName}}/pkg/frame"
)

func init() {
	global.RouterProvider.Provide(register{{.HandlerName}}API)
}

func register{{.HandlerName}}API(e *frame.Engine) {
	api := e.Group("/api")
	{
		api.Use(middleware.AuthMiddleware())
		// api.Use(middleware.JWTAuthMiddleware())
		// api.Use(middleware.CasbinMiddleware())
		// api.Use(middleware.UserLogMiddleware())
		pages := api.Group("/{{.handlerName2Dash}}s")
		{
			//project/:project_id/{{.handlerName2Dash}}s
			pages.GET("", controllers.{{.HandlerName}}PageList) //分页列表
			pages.GET("/:id", controllers.{{.HandlerName}}One)  //详情
		}
	}
}
