name: build

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: build
    runs-on: ${{ matrix.os }}
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: setup Go 1.20
        id: go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.20
      - name: build
        run: make build
      - name: install dependency
        run: if [ $(uname) == "Darwin" ]; then brew install gnu-sed ;fi
      - name: run Unit tests.
        run: go install github.com/go-delve/delve/cmd/dlv@latest && go test  ./... -v -covermode=count -coverprofile=coverage.txt
      - name: upload Coverage report to CodeCov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          verbose: true
